directive @CheckSchemas on FIELD | FIELD_DEFINITION
scalar GraphqlUpload

type AppSettings {
  salesRepresentative: Int!
  salesManager: Int!
  salesAdmin: Int!
  rolesAllowedToSeeMargin: [String]!
  representativeBalance: RepresentativeBalanceSettings!
}

type B2BOrder {
  costId: String!
  costCenterName: String!
  orderGroup: String!
  value: Float!
}

type Pagination {
  total: Int!
  page: Int!
  pageSize: Int!
}

type Query {
  checkOrderFormConfiguration: CheckOrderFormConfigurationResponse!
    @auth(scope: PUBLIC)

  getCart(id: ID!): SavedCart @auth(scope: PUBLIC) @CheckSchemas

  getSavedCarts(parentCartId: ID, getAll: Boolean): [SavedCart!]!
    @auth(scope: PUBLIC)
    @CheckSchemas

  getCartComments(savedCartId: ID!): [CartComment]!
    @auth(scope: PUBLIC)
    @CheckSchemas

  getAppSettings: AppSettings! @auth(scope: PUBLIC)

  getRepresentativeBalances: [RepresentativeBalance]!
    @auth(scope: PUBLIC)
    @CheckSchemas

  getRepresentativeBalanceByEmail(email: String): RepresentativeBalance
    @auth(scope: PUBLIC)
    @CheckSchemas

  getRepresentativeBalanceTransactions(
    email: String!
    page: Int
    pageSize: Int
    sort: String
  ): RepresentativeBalanceTransactionResponse!
    @auth(scope: PUBLIC)
    @CheckSchemas

  getAllPromotions: [Promotion!]! @auth(scope: PUBLIC)

  getComputedPrices(skuIds: [ID!]!): [ComputedPrice!]! @auth(scope: PUBLIC)
}

type Mutation {
  saveCart(
    id: ID
    title: String
    additionalData: String
    parentCartId: String
  ): SavedCart! @auth(scope: PUBLIC) @CheckSchemas

  updateSavedCartStatus(id: ID!, status: SavedCartStatus!): [SavedCart!]!
    @auth(scope: PUBLIC)
    @CheckSchemas

  updateSavedCartTitle(id: ID!, title: String!): SavedCart!
    @auth(scope: PUBLIC)
    @CheckSchemas

  createCartComment(savedCartId: ID!, comment: String!): CartComment!
    @auth(scope: PUBLIC)
    @CheckSchemas

  deleteCart(id: ID!): ID @auth(scope: PUBLIC) @CheckSchemas

  clearCart: UpdatedOrderForm! @auth(scope: PUBLIC)

  placeOrder(poNumber: String, invoiceData: InvoiceData): String
    @auth(scope: PUBLIC)

  updatePrices(
    items: [ItemsUpdatePriceInput]!
    title: String
    additionalData: String
  ): UpdatedOrderForm! @auth(scope: PUBLIC)

  saveRepresentativeBalance(
    email: String
    balance: Float!
    orderGroup: String!
    overwrite: Boolean
  ): RepresentativeBalance! @auth(scope: PUBLIC) @CheckSchemas

  saveRepresentativeBalanceSettings(
    enabled: Boolean!
    openingBalance: Float
    allowNegativeBalance: Boolean!
  ): RepresentativeBalanceSettings! @auth(scope: PUBLIC)

  shareCart(
    email: String!
    subject: String!
    title: String!
    linkLabel: String!
    linkHref: String!
    sentByLabel: String!
    userLabel: String!
    sentByName: String!
    sentByEmail: String!
    roleLabel: String!
    sentByRole: String!
    organizationLabel: String!
    sentByOrganization: String!
    costCenterLabel: String!
    sentByCostCenter: String!
    footerLine1: String!
    footerLine2: String!
  ): String! @auth(scope: PUBLIC)

  addItemsToCart(orderItems: [AddItemsToCartInput!]!): UpdatedOrderForm!
    @auth(scope: PUBLIC)

  updateItemsQuantity(
    orderItems: [UpdateItemsQuantityInput!]!
  ): UpdatedOrderForm! @auth(scope: PUBLIC)

  addAddressToCart(address: Address!): UpdatedOrderForm! @auth(scope: PUBLIC)

  updateSelectedAddresses(selectedAddresses: [Address!]!): UpdatedOrderForm!
    @auth(scope: PUBLIC)

  updateShippingOption(
    addressId: String
    itemIndexes: [Int!]
    selectedSla: String!
  ): UpdatedOrderForm! @auth(scope: PUBLIC)

  updateMultipleShippingOptions(
    input: [UpdateMultipleShippingOptionsInput!]!
  ): UpdatedOrderForm! @auth(scope: PUBLIC)

  uploadSpreadsheet(file: GraphqlUpload!): UpdatedOrderForm!
    @auth(scope: PUBLIC)
}
