name: Publish and Deploy App

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  publish_and_deploy:
    permissions:
      contents: write
    name: Publish and Deploy App
    runs-on: ubuntu-latest
    steps:
      - uses: cubos-vtex/vtex-publish-deploy-action@v15
        with:
          appKey: ${{ secrets.VTEX_TOOLBELT_KEY }}
          appToken: ${{ secrets.VTEX_TOOLBELT_TOKEN }}
